### ISSUE TITLE
Resource attributes to added to spans

### ISSUE THREAD

**Issue by JorritSalverda** [abdolence/opentelemetry-gcloud-trace-rs#55]
Similar to issue https://github.com/open-telemetry/opentelemetry-rust/issues/1261 this exporter doesn't add resource attributes to each span. This is helpful to set the `service.name` attribute though, which the default resource detectors extract from environment variable `OTEL_SERVICE_NAME`.

**Comment by abdolence** [comment]
Hi, thanks the reporting and working on PR 👍🏻

**Comment by abdolence** [comment]
Released in https://github.com/abdolence/opentelemetry-gcloud-trace-rs/releases/tag/v0.14.0
